---
title: "example_analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Load the package

```{r setup}
library(systemsseRology)
```

Read the data from an Excel file. Z-score the data and assign the label in the variable y.

```{r data}
library(readxl)
data <- as.data.frame(read_excel("../data/RSTR_data_NatureMedicine_subset.xlsx"))

X <- as.matrix(as.data.frame(lapply(data[, 5:ncol(data)], as.numeric)))
X_zscore <- scale(X, center = TRUE, scale = TRUE)
y <- factor(data$y, levels = unique(data$y))
```

The variable df_features contains information about the features, mainly used for visualization routines. 
Here, we assign a label (removing underscores) and extract the antigen. 

```{r annotation}
df_features <- data.frame(name = colnames(X))
df_features$label <- gsub("_", " ", df_features$name)
df_features$antigen <- gsub("_.*", "", df_features$name)
df_features$antigen <- factor(df_features$antigen)
df_features$feature_class <- rep(NA, length = nrow(df_features))
df_features$feature_class[which(grepl("IgG|IgA|IgM", df_features$name))] <- "titer"
df_features$feature_class[which(grepl("FcR", df_features$name))] <- "FcR"
df_features$feature_class <- factor(df_features$feature_class)
```

```{r PLSDA vis}
library(RColorBrewer)
# general options for plotting
opts_plot <- list()
opts_plot$df_features <- df_features

# Color assignment
opts_plot$colors = list(class = c(RSTR = "red", LTB = "blue"))
opts_plot$colors$antigen <- colorRampPalette(brewer.pal(name = "Dark2", n = 8))(nlevels(df_features$antigen))
names(opts_plot$colors$antigen) <- unique(df_features$antigen)
opts_plot$colors$feature_class <- colorRampPalette(brewer.pal(name = "Set1", n = 3))(nlevels(df_features$feature_class))
names(opts_plot$colors$feature_class) <- unique(df_features$feature_class)

opts_plot$loading_alpha <- 1 # transparency for the loadings
opts_plot$score_alpha <- 1 # transparency for the lcores
opts_plot$color_features <- "antigen" # which 
#opts_plot$color_features <- "feature_class"
opts_plot$LV_ind <- c(1,2) # which LVs to plot


# Perform a simple PCA using the interface function pca_ropls
model_pca <- pca_ropls(X)
plt_scores_pca <- visualize_ropls_scores(model_pca, y, options = opts_plot)
print(plt_scores_pca)

# Perform a PLS-DA and plot the scores and loadings
model <- train_ropls(X, y)
y_pred <- predict_ropls(model, X)
score_accuracy(y, y_pred)

plt_scores <- visualize_ropls_scores(model, y, options = opts_plot)
print(plt_scores)

plt_loadings <- visualize_ropls_loadings(model, options = opts_plot)
print(plt_loadings)

opts_plot$X <- X
opts_plot$y <- y
opts_plot$mark_enrichment <- TRUE
plt_loadings_bar <- visualize_ropls_loadings_bar(model, options = opts_plot)
print(plt_loadings_bar)

```

```{r cross-validate pls}
random_sel <- function(X, y) {
  total_features <- length(X[1, ])
  n_feats <- sample(1:total_features, 1)
  features <- sample(1:total_features, n_feats)
  return(features)
}


method = list(select = random_sel,
              train = train_pls,
              predict = predict_pls,
              score = score_accuracy)

opts = list(n_folds = 5, pt_trials = 3, rf_trials = 3)

return_vals <- validate(X, y, method, opts)
```


```{r cross-validate}
my_score <- function(y1, y2) {
   num1 <- as.numeric(y1)
   num2 <- as.numeric(y2)
   correct <- which(num1 == num2)
   return(length(correct) / length(y1))
}

random_sel <- function(X, y) {
  total_features <- length(X[1, ])
  n_feats <- sample(1:total_features, 1)
  features <- sample(1:total_features, n_feats)
  return(features)
}


method = list(select = random_sel,
              train = model_train,
              predict = model_predict,
              score = my_score)

opts = list(n_folds = 5, pt_trials = 3, rf_trials = 3)

return_vals <- validate(X, y, method, opts)
```
