---
title: "example_analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(systemsseRology)
```

```{r data}
library(readxl)
data <- as.data.frame(read_excel("../data/RSTR_data_NatureMedicine_subset.xlsx"))

X <- as.matrix(as.data.frame(lapply(data[, 5:ncol(data)], as.numeric)))
X_zscore <- scale(X, center = TRUE, scale = TRUE)
y <- factor(data$y, levels = unique(data$y))
```

```{r select features}
set.seed(42)
sel_features <- select_lasso(X_zscore, y)
```

```{r cross-validate pls}
random_sel <- function(X, y) {
  total_features <- length(X[1, ])
  n_feats <- sample(1:total_features, 1)
  features <- sample(1:total_features, n_feats)
  return(features)
}


score_2 <- function(y1, y2) {
  return(42)
}

method = list(select = random_sel,
              train = train_ropls,
              predict = predict_ropls,
              score = list(score_accuracy, score_2))

opts = list(n_folds = 5, pt_trials = 3, rf_trials = 3)

return_vals <- validate(X, y, method, opts)
```

