---
title: "R Notebook"
output: html_notebook
---

log10 nice tick labels

```{r}
scale_y_log10(breaks = 10^c(-10:10), #breaks = scales::trans_breaks("log10", function(x) 10^x),
              labels = scales::trans_format("log10", scales::math_format(10^.x)),
              limits = c(10^c(floor(min(log10(tmpDf$feature))), ceil(max(log10(tmpDf$feature)))))) + 
    annotation_logticks(sides = "l") +

```

```{r}

stat_compare_means(aes(label = paste0("p = ", ..p.format..),
                   #label =  "p.format", #"p.signif"
                   label.x = 1.5, 
                   #label.y = 10^(ceil(log10(max(dfBox$value))) + 0.1), 
                   #hide.ns = TRUE,
                   method = "wilcox.test")
```
                  
```{r}
paste0(formatC(p, digits = 3, format = "f"),)

theme(plot.title = element_text(size = 4))
```

```{r}
axis.text.x = element_text(size = 14,
                           angle = 60, hjust = 1)
```

```{r}
pltGraph <- ggraph(layout) +
  geom_edge_link(aes(color = r), edge_width = 3) +
  guides(edge_alpha = "none", edge_width = "none") +
  scale_edge_colour_gradient(low = "#56C1FF", high = "#005582") +
  geom_node_point(shape = 21, color = "gray", fill = nodeColours, size = 8, stroke = 0.5) +
  geom_node_text(aes(label = name), size = 3, point.padding = NA, box.padding = 0, force = 0.1, repel = T) +
  theme(aspect.ratio = 1) +
  theme_graph(background = "white", base_family = 'Helvetica') 
```


```{r}
ggplot(dfBox, aes(x = antigen, y = value, fill = class)) + 
    stat_boxplot(position = position_dodge(width = 0.75), geom = 'errorbar', width = 0.2) + 
    geom_boxplot(outlier.shape = NA) + 
    geom_point(position = position_jitterdodge(), shape = 21, size = 1, aes(fill = class), color = "black") + 
    scale_fill_manual(values = myColors$class) + 
    theme_classic() + 
    theme(legend.position = "none",
          #axis.title = element_text(size = 12),
          #axis.text.x = element_text(colour = c(myColors$antigen[ag]), size = 12),
          #plot.title = element_text(hjust = 0.5, size = 12)
          ) 
```

```{r}
pValLabels[1, which(pValMed < 0.0005)] <- "***"
pValLabels[1, which(pValMed > 0.0005 & pValMed < 0.005)] <- "**"
pValLabels[1, which(pValMed > 0.005 & pValMed < 0.05)] <- "*"

pValLabels[2, which(pValMAD < 0.0005)] <- "***"
pValLabels[2, which(pValMAD > 0.0005 & pValMAD < 0.005)] <- "**"
pValLabels[2, which(pValMAD > 0.005 & pValMAD < 0.05)] <- "*"

changeHeat <- data.frame(matrix(nrow = 2, ncol = dim(X)[2]))
rownames(changeHeat) <- c("change in median","change in MAD")
colnames(changeHeat) <- colnames(X_unscaledReordered)
changeHeat[1,] <- changeMed 
changeHeat[2,] <- changeMAD

myBreaks <- c(seq(min(changeHeat), 0, length.out=ceiling(100/2) + 1), 
              seq(max(changeHeat)/100, max(changeHeat), length.out=floor(50)))

pdf("Figures/changeMedMAD_Ig.pdf", width = 10, height = 3) 
p <- pheatmap(changeHeat[, grepl("Ig",colnames(changeHeat))], 
         cluster_rows = FALSE, cluster_cols = FALSE, cellwidth = 15, cellheight = 15, 
         display_numbers = pValLabels[, which(grepl("Ig",colnames(changeHeat)))], breaks = myBreaks)  
```

